"""Initial migration.

Revision ID: 63d78982103d
Revises: 
Create Date: 2025-01-28 11:40:16.775712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d78982103d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_name', sa.String(length=100), nullable=False),
    sa.Column('bot_description', sa.String(length=500), nullable=True),
    sa.Column('bot_welcome', sa.String(length=500), nullable=False),
    sa.Column('bot_avatar', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
