"""empty message

Revision ID: 7e6180f301a4
Revises: 63d78982103d
Create Date: 2025-02-12 22:30:58.203321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6180f301a4'
down_revision = '63d78982103d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_trigger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_competences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_client_active', sa.Boolean(), nullable=True),
    sa.Column('service_client_niveau', sa.String(length=20), nullable=True),
    sa.Column('_service_client_domains', sa.Text(), nullable=True),
    sa.Column('lead_gen_active', sa.Boolean(), nullable=True),
    sa.Column('_lead_qualification', sa.Text(), nullable=True),
    sa.Column('support_tech_active', sa.Boolean(), nullable=True),
    sa.Column('support_tech_niveau', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('communication_style', sa.String(length=50), nullable=True),
    sa.Column('language_level', sa.String(length=50), nullable=True),
    sa.Column('personality_traits', sa.Text(), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('goodbye_message', sa.Text(), nullable=True),
    sa.Column('fallback_message', sa.Text(), nullable=True),
    sa.Column('redirect_message', sa.Text(), nullable=True),
    sa.Column('technical_error', sa.Text(), nullable=True),
    sa.Column('invalid_data', sa.Text(), nullable=True),
    sa.Column('service_unavailable', sa.Text(), nullable=True),
    sa.Column('vocabulary', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('default_duration', sa.Integer(), nullable=True),
    sa.Column('calendar_id', sa.String(length=200), nullable=True),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('flow_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('variables', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_redirection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('api_key', sa.String(length=200), nullable=True),
    sa.Column('subdomain', sa.String(length=100), nullable=True),
    sa.Column('priority_mapping', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['conversation_flow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow_variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('var_type', sa.String(length=50), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['conversation_flow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('response_template', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_node_id'], ['flow_node.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['flow_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_connection')
    op.drop_table('response_rule')
    op.drop_table('flow_variable')
    op.drop_table('flow_node')
    op.drop_table('faq')
    op.drop_table('document')
    op.drop_table('user')
    op.drop_table('ticket_config')
    op.drop_table('knowledge_category')
    op.drop_table('form_redirection')
    op.drop_table('email_template')
    op.drop_table('conversation_flow')
    op.drop_table('calendar_config')
    op.drop_table('bot_responses')
    op.drop_table('bot_competences')
    op.drop_table('action_trigger')
    # ### end Alembic commands ###
