"""Add Claude API support

Revision ID: add_claude_support
Revises: b98b430c1779
Create Date: 2025-11-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_claude_support'
down_revision = 'b98b430c1779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_claude_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('claude_model', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('claude_model')
        batch_op.drop_column('encrypted_claude_key')

    # ### end Alembic commands ###
