"""Add UI mode preferences

Revision ID: add_ui_mode_preferences
Revises: add_claude_support
Create Date: 2025-11-15 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_ui_mode_preferences'
down_revision = 'add_claude_support'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_completed', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('ui_mode', sa.String(length=20), nullable=True, server_default='simple'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ui_mode')
        batch_op.drop_column('onboarding_completed')

    # ### end Alembic commands ###
