"""Ajout colonnes API utilisateur

Revision ID: c2573821d65b
Revises: d32337763005
Create Date: 2025-05-26 13:54:04.484238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2573821d65b'
down_revision = 'd32337763005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_openai_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('encrypted_mistral_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('openai_model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mistral_model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('preferred_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('api_usage_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('api_usage_current', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('api_usage_reset_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('api_usage_reset_date')
        batch_op.drop_column('api_usage_current')
        batch_op.drop_column('api_usage_limit')
        batch_op.drop_column('preferred_provider')
        batch_op.drop_column('login_count')
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('mistral_model')
        batch_op.drop_column('openai_model')
        batch_op.drop_column('current_provider')
        batch_op.drop_column('encrypted_mistral_key')
        batch_op.drop_column('encrypted_openai_key')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
