"""Rename metadata to integration_metadata in IntegrationLog

Revision ID: rename_metadata
Revises: add_ui_mode_preferences
Create Date: 2025-11-17 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'rename_metadata'
down_revision = 'add_ui_mode_preferences'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration_log', schema=None) as batch_op:
        batch_op.alter_column('metadata',
                              new_column_name='integration_metadata',
                              existing_type=sa.Text(),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration_log', schema=None) as batch_op:
        batch_op.alter_column('integration_metadata',
                              new_column_name='metadata',
                              existing_type=sa.Text(),
                              nullable=True)

    # ### end Alembic commands ###
